channels:
  - defaults
  - conda-forge
dependencies:
  # for julia GMT package
  - gmt=6.1.*
  # servers/proxies
  - psycopg2=2.8.*
  # conda ui package manager
  - jupyter_conda=3.4.*
  # r packages
  - r-base=3.6.*
  - r-caret=6.*
  - r-crayon=1.3*
  - r-devtools=2.3*
  - r-forecast=8.12*
  - r-hexbin=1.28*
  - r-htmltools=0.4*
  - r-htmlwidgets=1.5*
  - r-nycflights13=1.0*
  - r-randomforest=4.6*
  - r-rcurl=1.98*
  - r-rmarkdown=2.2*
  - r-rodbc=1.3*
  - r-rsqlite=2.2*
  - r-shiny=1.4*
  - r-tidyverse=1.3*
  - r-tidymodels=0.1*
  # kernels
  - scijava-jupyter-kernel=0.6.*
  - xeus-cling=0.9.*
  # process manager
  - tini=0.18.0
  # python/pip packages
  - pip
  - pip:
    - autopep8==1.5.3
    - chart-studio==1.1
    - dash==1.12
    - flake8==3.8.3
    - fredapi==0.4.2
    - jupyter-contrib-nbextensions==0.5
    - jupyter-dash==0.3.0
    - jupyterhub==1.1.0
    - matplotlib==3.3.0
    - nbgitpuller==0.8.0
    - nbresuse==0.3.*
    - otter-grader==1.0.0.b9
    - plotly==4.9.0
    - plotly-charts==0.5
    - plotly-geo==1.0
    - python-language-server==0.33.3
    - tensorflow==2.2.0
    - yellowbrick==1.1
    - xgboost==1.1.1
