channels:
  - defaults
  - conda-forge
dependencies:
  # we don't really need tini as it's replace by the standard docker --init
  # flag, but add it to maintain compatibility with jupyter/docker-stacks
  - tini=0.18.0

  # the psycopg2 package is always required,
  # since the illumidesk stack depends on Postgress
  - psycopg2=2.8.*

  # use python 3.8 as the default
  - python=3.8.5

  # add r packages if needed, for example
  # - r-base=3.6.*
  # - r-caret=6.*

  # you can also add additional kernels. for example,
  # - xeus-cling=0.9.*

  # python/pip packages
  - pip
  - pip:
    # add these packages to all features to work
    - jupyter-contrib-nbextensions==0.5
    - jupyterhub==1.1.0
    - nbgitpuller==0.8.0
    - nbresuse==0.3.*
    # add more pip packages as needed, for example:
    # - matplotlib==3.3.0
