dependencies:
  - r-base=4.0.0
#   - r-caret=6.*
#   - r-crayon=1.3*
#   - r-devtools=2.3*
#   - r-forecast=8.12*
#   - r-hexbin=1.28*
#   - r-htmltools=0.4*
#   - r-htmlwidgets=1.5*
#   - r-irkernel=1.1*
#   - r-nycflights13=1.0*
#   - r-plyr=1.8*
#   - rpy2=3.1*
#   - r-randomforest=4.6*
#   - r-rcurl=1.98*
#   - r-reshape2=1.4*
#   - r-rmarkdown=2.2*
#   - r-rodbc=1.3*
#   - r-rsqlite=2.2*
#   - r-shiny=1.4*
#   - r-tidyverse=1.3*
#   - unixodbc=2.3.*
#   - r-tidymodels=0.1*
#   - r-tidyverse=1.3*
#   - rpy2=3.1*
