#!/bin/bash

enable_classicextensions () {
    cd "/home/${NB_USER}"
    # community extensions
    jupyter contrib nbextension install --sys-prefix
    # widgets
    jupyter nbextension enable --py widgetsnbextension --sys-prefix
}

install_labextensions () {
    # Add jupyterlab extensions
    jupyter labextension install @jupyter-widgets/jupyterlab-manager@^2.0.0
}

install_jupyter_server_proxy () {
    jupyter serverextension enable --sys-prefix --py jupyter_server_proxy
    jupyter labextension install @jupyterlab/server-proxy@^2.1.1
    jupyter lab build -y
    jupyter lab clean -y
    npm cache clean --force
    rm -rf "${HOME}/.cache/yarn"
    rm -rf "${HOME}/.node-gyp"
    fix-permissions "${CONDA_DIR}"
    fix-permissions "${HOME}"
}

cleanup () {
    # clean lab extensions and npm files
    jupyter lab clean -y
    npm cache clean --force
    # delete items explicitly since we don't want to delete hidden files/folders
    # such as the .jupyter or .local folders
    rm -rf "/home/${NB_USER}/.cache/yarn"
    rm -rf "/home/${NB_USER}/.node-gyp"
    rm -rf "/home/${NB_USER}/apt.txt"
    rm -rf "/home/${NB_USER}/npm*"
    rm -rf "/home/${NB_USER}/environment.yml*"
    rm -rf "/home/${NB_USER}/postBuild*"
    conda clean --all -y
}

main () {
    enable_classicextensions
    install_labextensions
    install_jupyter_server_proxy
    cleanup
}
