name: Test and Build

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env
      - name: Build Docker Images
        run: make -C main build-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Test Docker Images
        run: pytest -v
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/main'
        run: make -C main push-all